### PR TITLE
Fix objects which should be arrayObjects

### PR DESCRIPTION
**Pull request by Rid**
This fix ensures that all objects are generated as arrayObjects using the fix from https://github.com/janephp/janephp/pull/704

Until the patch is merged, the jane-php fix will need to be applied manually to the vendor/ folder.

### CODE REVIEW

**Comment by Rid** [comment]
@flavioheleno could this be merged and a new version pushed to packagist?

**Comment by flavioheleno** [comment]
hey @Rid, ideally this should be a patch, so it could be re-applied in case of re-generating the code, could you do it using that format instead?

**Comment by Rid** [comment]
@flavioheleno Do you mean patching janephp in the vendor folder? I think patching our code for this particular bug is probably too much as it's affecting so many lines, it's likely for patches to fail between docker api specs and different janephp versions.

Pushing this version would be a stop-gap until janephp release a version with the fix.

**Comment by flavioheleno** [comment]
I actually meant patching our own generated code as we do witht he other patches in the patches folder, but what you said about the soze of the patch also bothers me.
I think we may need an "upgrading" file just like the one in php-src, so we can keep tabs on this kind of fix.
Anyways, I'm merging this. Thank you for all your work!

**Pull request merged**
